#!/bin/bash

CC=icpc
CFLAGS=-c -O3 -Ofast -fopenmp -I/usr/local/openbabel/include/openbabel-2.0 -I/usr/include/eigen3 -DBUILD=0
LDFLAGS=-lz -L/usr/local/openbabel/lib -lopenbabel -liomp5 -lpthread
SOURCES=McConf.cpp McGrid.cpp MrPocket.cpp mol2_rmsd.cpp McColony.cpp FESummation.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: McConf McGrid mol2_rmsd MrPocket McColony McSummation
	mv McConf McGrid mol2_rmsd McPocket McColony McSummation ../../release/

McConf: McConf.o
	$(CC) McConf.o -o McConf $(LDFLAGS)

McGrid: McGrid.o
	$(CC) McGrid.o -o McGrid $(LDFLAGS)

mol2_rmsd: mol2_rmsd.o
	$(CC) mol2_rmsd.o -o mol2_rmsd $(LDFLAGS)

MrPocket: MrPocket.o
	$(CC) MrPocket.o -o McPocket $(LDFLAGS)

McColony: McColony.o 
	$(CC) McColony.o -o McColony $(LDFLAGS)

McSummation: FESummation.o
	$(CC) FESummation.o -o McSummation $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm $(OBJECTS) McConf McGrid mol2_rmsd McPocket
